// flow-typed signature: 34db3707c84e24fbe7f28517299b1212
// flow-typed version: <<STUB>>/popsicle_v9.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'popsicle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'popsicle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'popsicle/dist/base' {
  declare module.exports: any;
}

declare module 'popsicle/dist/browser' {
  declare module.exports: any;
}

declare module 'popsicle/dist/browser/form-data' {
  declare module.exports: any;
}

declare module 'popsicle/dist/browser/tough-cookie' {
  declare module.exports: any;
}

declare module 'popsicle/dist/common' {
  declare module.exports: any;
}

declare module 'popsicle/dist/error' {
  declare module.exports: any;
}

declare module 'popsicle/dist/form' {
  declare module.exports: any;
}

declare module 'popsicle/dist/index' {
  declare module.exports: any;
}

declare module 'popsicle/dist/jar' {
  declare module.exports: any;
}

declare module 'popsicle/dist/plugins/browser' {
  declare module.exports: any;
}

declare module 'popsicle/dist/plugins/common' {
  declare module.exports: any;
}

declare module 'popsicle/dist/plugins/index' {
  declare module.exports: any;
}

declare module 'popsicle/dist/plugins/is-host/browser' {
  declare module.exports: any;
}

declare module 'popsicle/dist/plugins/is-host/index' {
  declare module.exports: any;
}

declare module 'popsicle/dist/request' {
  declare module.exports: any;
}

declare module 'popsicle/dist/response' {
  declare module.exports: any;
}

declare module 'popsicle/dist/support' {
  declare module.exports: any;
}

declare module 'popsicle/dist/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'popsicle/dist/base.js' {
  declare module.exports: $Exports<'popsicle/dist/base'>;
}
declare module 'popsicle/dist/browser.js' {
  declare module.exports: $Exports<'popsicle/dist/browser'>;
}
declare module 'popsicle/dist/browser/form-data.js' {
  declare module.exports: $Exports<'popsicle/dist/browser/form-data'>;
}
declare module 'popsicle/dist/browser/tough-cookie.js' {
  declare module.exports: $Exports<'popsicle/dist/browser/tough-cookie'>;
}
declare module 'popsicle/dist/common.js' {
  declare module.exports: $Exports<'popsicle/dist/common'>;
}
declare module 'popsicle/dist/error.js' {
  declare module.exports: $Exports<'popsicle/dist/error'>;
}
declare module 'popsicle/dist/form.js' {
  declare module.exports: $Exports<'popsicle/dist/form'>;
}
declare module 'popsicle/dist/index.js' {
  declare module.exports: $Exports<'popsicle/dist/index'>;
}
declare module 'popsicle/dist/jar.js' {
  declare module.exports: $Exports<'popsicle/dist/jar'>;
}
declare module 'popsicle/dist/plugins/browser.js' {
  declare module.exports: $Exports<'popsicle/dist/plugins/browser'>;
}
declare module 'popsicle/dist/plugins/common.js' {
  declare module.exports: $Exports<'popsicle/dist/plugins/common'>;
}
declare module 'popsicle/dist/plugins/index.js' {
  declare module.exports: $Exports<'popsicle/dist/plugins/index'>;
}
declare module 'popsicle/dist/plugins/is-host/browser.js' {
  declare module.exports: $Exports<'popsicle/dist/plugins/is-host/browser'>;
}
declare module 'popsicle/dist/plugins/is-host/index.js' {
  declare module.exports: $Exports<'popsicle/dist/plugins/is-host/index'>;
}
declare module 'popsicle/dist/request.js' {
  declare module.exports: $Exports<'popsicle/dist/request'>;
}
declare module 'popsicle/dist/response.js' {
  declare module.exports: $Exports<'popsicle/dist/response'>;
}
declare module 'popsicle/dist/support.js' {
  declare module.exports: $Exports<'popsicle/dist/support'>;
}
declare module 'popsicle/dist/test/index.js' {
  declare module.exports: $Exports<'popsicle/dist/test/index'>;
}
